import type { jsPDF } from "jspdf";

type Check = {
  name?: string;
  status?: string;
  message?: string;
  recommendation?: string;
};

type ModuleBlock = {
  score?: number;
  checks?: Check[];
  error?: string;
};

type AuditResult = {
  url: string;
  overall_score: number;
  timestamp?: string;
  modules?: Record<string, ModuleBlock>;
};

const MODULE_ORDER = [
  ["seo", "SEO"],
  ["performance", "Performance"],
  ["accessibility", "Accessibility"],
  ["security", "Security"],
  ["gdpr", "GDPR"],
] as const;

function safeText(value: unknown, max = 220): string {
  const s = String(value ?? "").replace(/\s+/g, " ").trim();
  return s.length > max ? `${s.slice(0, max - 1)}…` : s;
}

function addWrapped(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  lineHeight = 5
): number {
  const lines = doc.splitTextToSize(text, maxWidth) as string[];
  doc.text(lines, x, y);
  return y + lines.length * lineHeight;
}

export async function downloadAuditPdf(
  result: AuditResult,
  opts: { title: string; brand?: string }
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const margin = 16;
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const maxW = pageW - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(opts.brand || "WebHealthIQ", margin, y);
  y += 8;

  doc.setFontSize(13);
  doc.text(opts.title, margin, y);
  y += 7;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y = addWrapped(doc, result.url, margin, y, maxW);
  y += 3;
  doc.text(`Score: ${result.overall_score}/100`, margin, y);
  y += 5;
  if (result.timestamp) {
    doc.setTextColor(100);
    doc.text(result.timestamp, margin, y);
    doc.setTextColor(0);
    y += 6;
  } else {
    y += 3;
  }

  doc.setDrawColor(200);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  for (const [key, label] of MODULE_ORDER) {
    const mod = result.modules?.[key];
    if (!mod) continue;

    ensureSpace(18);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    const score = typeof mod.score === "number" ? mod.score : "—";
    doc.text(`${label}: ${score}/100`, margin, y);
    y += 6;

    if (mod.error) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      y = addWrapped(doc, safeText(mod.error, 400), margin, y, maxW, 4.5);
      y += 4;
      continue;
    }

    const checks = Array.isArray(mod.checks) ? mod.checks : [];
    for (const check of checks.slice(0, 12)) {
      ensureSpace(16);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      const status = (check.status || "?").toUpperCase();
      y = addWrapped(
        doc,
        `[${status}] ${safeText(check.name || "Check", 80)}`,
        margin,
        y,
        maxW,
        4.5
      );
      doc.setFont("helvetica", "normal");
      if (check.message) {
        y = addWrapped(doc, safeText(check.message), margin + 2, y, maxW - 2, 4.2);
      }
      if (check.recommendation) {
        doc.setTextColor(60);
        y = addWrapped(
          doc,
          `→ ${safeText(check.recommendation)}`,
          margin + 2,
          y,
          maxW - 2,
          4.2
        );
        doc.setTextColor(0);
      }
      y += 3;
    }
    y += 3;
  }

  ensureSpace(10);
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Generated by WebHealthIQ · webhealthiq.com", margin, pageH - 10);

  const host = result.url.replace(/^https?:\/\//, "").replace(/[^\w.-]+/g, "_").slice(0, 40);
  doc.save(`webhealthiq-${host || "report"}.pdf`);
}
